# QR Algorithm

Ci sono delle proprietà:

- Dato che gli eigenvalue di una matrice tirangolare sono gli elementi sulla diagonale, questo algoritmo permette di trovarli.
- Similarity transformation preserva gli eigenvalue.

La matrice A viene **decomposta** in A = QR dove Q è ortogonale e R è triangolare superiore.

## Gram-Schmidt
Come prima implementazione proviamo con l'algoritmo di **Gram-Schmidt**


In [1]:
import numpy as np
from itertools import product
from math import copysign, hypot




In [2]:
def print_matrix(matrix):
    s = [[str(e) for e in row] for row in matrix]
    lens = [max(map(len, col)) for col in zip(*s)]
    fmt = '\t'.join('{{:{}}}'.format(x) for x in lens)
    table = [fmt.format(*row) for row in s]
    print('\n'.join(table))
    return

In [12]:
def qr_decomp_gram_schmidt(A):
    m, n = A.shape
    rank = np.linalg.matrix_rank(A)

    if rank < n:
        print(f"Il rango della matrice è {rank} il quale è inferiore del numero delle colonne {n}!")
    
    Q = np.zeros((m, n))
    
    for i, column in enumerate(A.T):
        Q[:,i] = column

        for prev in Q.T[:i]:
            Q[:,i] -= (prev @ column) / (prev @ prev) * prev
    
    Q /= np.linalg.norm(Q,axis=0)
    R = Q.T @ A

    return Q, R

In [13]:
# Tests

#TODO: rendere i test non dipendenti da una sola funzione

def test_orthonormality(A):
    Q, _ = qr_decomp_gram_schmidt(A)
    I = Q.T @ Q

    assert len(set(I.shape)) == 1, "L'identità computata deve essere una matrice quadrata!"
    assert np.allclose(I, np.eye(I.shape[0])), "L'identità  computata deve essere una matrice identità!"

def test_upper_triangular(A):
    _, R = qr_decomp_gram_schmidt(A)

    assert len(set(R.shape)) == 1, "La matrice triangolare superiore computata dovrebbe essere una matrice quadrata!"

    for i, row in enumerate(R):
        assert np.allclose(row[:i], 0), f"La riga {i} della matrice triangolare superiore calcolata non è giusta!"

def test_multiplication(A):
    Q,R = qr_decomp_gram_schmidt(A)
    
    assert np.allclose(Q @ R, A), "La moltiplicazione fra le matrici ottenute non restituisce la matrice originaria!"

In [14]:
test_matricies = (
    np.random.random((2, 2)),
    np.random.random((5, 2)),
    np.random.random((5, 5)),
    np.random.random((9, 8)),
)

tests = (
    test_orthonormality,
    test_upper_triangular,
    test_multiplication,
)

for test, matrix in product(tests, test_matricies):
    test(matrix)

print("tutti i test sono superati")

tutti i test sono superati


# Givens Rotation
proviamo ad implementare le givens rotation per migliorare la velocità di esecuzione.

In [25]:
def qr_decomp_givens_rotation(A):

    (num_rows, num_cols) = np.shape(A)
    if num_rows == num_cols: 
        # Initialize Q,R
        # Q = orthogonal matrix
        # R =  upper triangular matrix
        Q = np.identity(num_rows)
        R = np.copy(A)

        # Iterate over lower triangular matrix.
        (rows, cols) = np.tril_indices(num_rows, -1, num_cols)
        #print(rows, cols)
        for (row, col) in zip(rows, cols):

            # Compute Givens rotation matrix and
            # zero-out lower triangular matrix entries.
            if R[row, col] != 0:
                (c, s) = Givens_Rotation_Matrix_Entries(R[col, col], R[row, col])

                G = np.identity(num_rows)
                G[[col, row], [col, row]] = c
                G[row, col] = s
                G[col, row] = -s

                R = np.dot(G, R)
                Q = np.dot(Q, G.T)
                #R = G @ R
                #Q = Q @ G.T
        return Q, R
    else:
        Q = np.eye(num_rows)
        R = np.copy(A)

        rows, cols = np.tril_indices(num_rows, -1, num_cols)
        for (row, col) in zip(rows, cols):
            # If the subdiagonal element is nonzero, then compute the nonzero 
            # components of the rotation matrix
            if R[row, col] != 0:
                r = np.sqrt(R[col, col]**2 + R[row, col]**2)
                c, s = R[col, col]/r, -R[row, col]/r

                # The rotation matrix is highly discharged, so it makes no sense 
                # to calculate the total matrix product
                R[col], R[row] = R[col]*c + R[row]*(-s), R[col]*s + R[row]*c
                Q[:, col], Q[:, row] = Q[:, col]*c + Q[:, row]*(-s), Q[:, col]*s + Q[:, row]*c

        return Q[:, :num_cols], R[:num_cols]



##### Compute matrix entries for Givens rotation. #####

def Givens_Rotation_Matrix_Entries(a, b):
    r = hypot(a, b)
    c = a/r
    s = -b/r

    return (c, s)

In [23]:
def test_orthonormality(A):
    Q, _ = qr_decomp_givens_rotation(A)
    I = Q.T @ Q

    assert len(set(I.shape)) == 1, "L'identità computata deve essere una matrice quadrata!"
    assert np.allclose(I, np.eye(I.shape[0])), "L'identità  computata deve essere una matrice identità!"

def test_upper_triangular(A):
    _, R = qr_decomp_givens_rotation(A)

    assert len(set(R.shape)) == 1, "La matrice triangolare superiore computata dovrebbe essere una matrice quadrata!"

    for i, row in enumerate(R):
        assert np.allclose(row[:i], 0), f"La riga {i} della matrice triangolare superiore calcolata non è giusta!"

def test_multiplication(A):
    Q, R = qr_decomp_givens_rotation(A)
    
    assert np.allclose(Q @ R, A), "La moltiplicazione fra le matrici ottenute non restituisce la matrice originaria!"

In [29]:
test_matricies = (
    np.random.random((3, 3)),
    np.random.random((4, 5)),
    np.random.random((5, 5)),
    np.random.random((9, 8)),
)

tests = (
    test_orthonormality,
    test_multiplication,
)

for test, matrix in product(tests, test_matricies):
    test(matrix)

print("tutti i test sono superati")

tutti i test sono superati


In [26]:
A = np.random.random((4, 4))

Q, R = qr_decomp_givens_rotation(A)

print(A)
print(Q)
print(R)

print(Q @ R)

[[0.39926392 0.77770333 0.86150654 0.99774404]
 [0.54909614 0.96948566 0.71784402 0.08072706]
 [0.58422336 0.64957978 0.68166213 0.5432887 ]
 [0.73168753 0.70449762 0.41615202 0.66714856]]
[[ 0.39224754  0.0863236  -0.82561526 -0.39629477]
 [ 0.          0.97708796  0.          0.21283588]
 [ 0.57395662  0.1263131   0.5642335  -0.57987874]
 [ 0.71882937 -0.14796064  0.          0.67925841]]
[[ 1.01788765e+00  1.18429642e+00  1.02831061e+00  1.18275278e+00]
 [ 5.36515233e-01  9.92219425e-01  8.00293824e-01  1.34919044e-01]
 [-2.62225490e-17 -2.75569064e-01 -3.26656339e-01 -5.17211022e-01]
 [ 1.16867363e-01  1.05207765e-17 -3.01234187e-01 -2.40094428e-01]]
[[0.39926392 0.77770333 0.86150654 0.99774404]
 [0.54909614 0.96948566 0.71784402 0.08072706]
 [0.58422336 0.64957978 0.68166213 0.5432887 ]
 [0.73168753 0.70449762 0.41615202 0.66714856]]


# Unshifted QR similarità di Hessenberg

con questo metodo si prova a creare una matrice di Hessenberg simile a quelle di partenza applicando gli housolder reflector, lasciando invariati gli autovalori

In [63]:
# da vedere se serve
'''
def Hessenberg_reduction(A):
    n = np.size(A,1)
    H = A
    if(n > 2):
        a1 = A[2:n, 1]
        e1 = np.zeros(n-2)
        e1[1] = 1
        sgn = np.sign(a1[1])
        v = a1 + sgn*np.linalg.norm(a1)*e1
        v = v/np.linalg.norm(v)
        Q1 = np.eye(n-2) - 2*(v*v.T)
        A[2:n, 1] = Q1@ A[2:n, 1]
        A[1, 2:n] = Q1@A[1, 2:n]
        A[2:n, 2:n] = Q1@A[2:n, 2:n]@Q1.T
        H = Hessenberg_reduction(A[2:n, 2:n])
    else:
        H = np.copy(A)
    return A
'''
def Givens_Rotation_Matrix_Entries(a, b):
    r = hypot(a, b)
    c = a/r
    s = b/r
    return c, s


def Hessenberg_reduction(A):
    # mi trovo gli indici della sottodiagonale corrispondente agli elementi da azzerare
    (num_rows, num_cols) = np.shape(A)
    (rows, cols) = np.tril_indices(num_rows, -2, num_cols)
    #print(rows,cols)
    #index = zip(rows, cols)
    #print(index)
    #itero sugli indici appena trovati 
    for (col, row) in sorted(zip(cols, rows)):
    #controlla se l'elemento da azzerare è già uguale a zero
        print(row, col)
        if A[row, col] != 0:
            # trova gli indici della matrice di givens unando come pivot [col, col](sempre != 0)
            c, s = Givens_Rotation_Matrix_Entries(A[col,col], A[row, col])
            
            #si costruisce la matrice di givens partendo dall'identità
            G = np.identity(num_rows)
            #assegna gli indici trovati precedentemente alla matrice di givens
            G[col, col] = c
            G[row, row] = c
            G[row, col] = -s
            G[col, row] = s
            # annichilisce l'elemento in posizione A[row, col]
            A = G @ A
            
            print("-----------------------------------------")
    return A

In [64]:
A = np.random.random((5, 5))
#print_matrix(A)
A = Hessenberg_reduction(A)
print("-------------------------------------------------------------")
print_matrix(A)

2 0
-----------------------------------------
3 0
-----------------------------------------
4 0
-----------------------------------------
3 1
-----------------------------------------
4 1
-----------------------------------------
4 2
-----------------------------------------
-------------------------------------------------------------
0.8377955526570058 	0.6224276679030574    	0.7505741752499596 	1.256029293109885   	0.6871812173709613 
0.40460879444606423	0.6188241804781464    	0.7445787575584891 	0.633672241255206   	0.805557773745107  
0.14482969903140244	0.16057347642661607   	0.11967711816791898	-0.13914772852146512	0.2174753591086757 
0.09748653897192412	2.0726059769446304e-18	0.4951716059105419 	0.20609894434532466 	0.30350413406280735
0.11356509599033628	-0.20477954128856402  	8.9055994462659e-18	-0.8171262333248429 	-0.8043776167563778


In [ ]:
test_matricies = (
    hessenberg(np.random.random((3, 3))),
    hessenberg(np.random.random((4, 4))),
    hessenberg(np.random.random((5, 5))),
    hessenberg(np.random.random((9, 9))),
)

tests = (
    test_orthonormality,
    test_multiplication,
)

for test, matrix in product(tests, test_matricies):
    test(matrix)

print("tutti i test sono superati")